import type {
  ActivityLogItem,
  AppDataState,
  BookingItem,
  DestinationCard,
  NotificationItem,
  Post,
  StoryItem,
  Trip,
  UserProfile,
} from "../types";

export const demoUsers: UserProfile[] = [
  {
    uid: "u1",
    name: "Ava Mitchell",
    email: "ava@email.com",
    role: "admin",
    status: "active",
    bio: "Beach lover and logistics wizard.",
    location: "Bali",
    notifications: "on",
    style: "relaxation",
    createdAt: new Date("2026-01-10"),
  },
  {
    uid: "u2",
    name: "Marco Rivera",
    email: "marco@email.com",
    role: "traveler",
    status: "active",
    bio: "Adventure junkie building routes people can actually follow.",
    location: "Madrid",
    notifications: "on",
    style: "adventure",
    createdAt: new Date("2026-02-04"),
  },
  {
    uid: "u3",
    name: "Sofia Chen",
    email: "sofia@email.com",
    role: "traveler",
    status: "pending",
    bio: "Food-focused city traveler.",
    location: "Singapore",
    notifications: "on",
    style: "food",
    createdAt: new Date("2026-03-11"),
  },
];

export const demoTrips: Trip[] = [
  {
    id: "t1",
    name: "Bali Beach Escape",
    destination: "Bali, Indonesia",
    startDate: "2026-06-12",
    endDate: "2026-06-18",
    vibe: "Beach",
    category: "Relaxation",
    status: "confirmed",
    progress: 72,
    groupSize: 6,
    currency: "USD",
    budgetTotal: 3800,
    adminId: "u1",
    shareCode: "BALI-72",
    members: [
      { uid: "u1", name: "Ava Mitchell", email: "ava@email.com", role: "admin", joinedAt: new Date("2026-02-03") },
      { uid: "u2", name: "Marco Rivera", email: "marco@email.com", role: "member", joinedAt: new Date("2026-02-08") },
      { uid: "u3", name: "Sofia Chen", email: "sofia@email.com", role: "pending", joinedAt: new Date("2026-02-10") },
    ],
    itinerary: [
      {
        id: "d1",
        label: "Arrival",
        date: "2026-06-12",
        activities: [
          {
            id: "a1",
            name: "Airport pickup",
            type: "transport",
            time: "10:30",
            icon: "Shuttle",
            location: "Ngurah Rai Airport",
            notes: "Meet outside terminal 2.",
            votes: [{ userId: "u1", value: "up" }],
          },
          {
            id: "a2",
            name: "Villa check-in",
            type: "hotel",
            time: "13:00",
            icon: "Hotel",
            location: "Seminyak",
            notes: "Poolside rooms with late lunch booking.",
            votes: [{ userId: "u2", value: "up" }],
          },
        ],
      },
      {
        id: "d2",
        label: "Beach Day",
        date: "2026-06-13",
        activities: [
          {
            id: "a3",
            name: "Sunset boat tour",
            type: "tour",
            time: "17:30",
            icon: "Boat",
            location: "Jimbaran Bay",
            notes: "Book 48 hours in advance.",
            votes: [{ userId: "u1", value: "up" }, { userId: "u2", value: "up" }],
          },
        ],
      },
    ],
    budget: [
      {
        id: "b1",
        label: "Flights",
        amount: 1200,
        actual: 1280,
        category: "flights",
        currency: "USD",
        paidBy: "u1",
        splitBetween: ["u1", "u2", "u3"],
        emoji: "Flight",
      },
      {
        id: "b2",
        label: "Villa",
        amount: 850,
        actual: 840,
        category: "hotels",
        currency: "USD",
        paidBy: "u1",
        splitBetween: ["u1", "u2", "u3"],
        emoji: "Stay",
      },
    ],
    comments: [
      { id: "c1", userId: "u2", authorName: "Marco Rivera", text: "Can we keep one evening free for local food spots?", createdAt: new Date("2026-03-01") },
    ],
    packingList: ["Passport", "Sunscreen", "Power adapter", "Swimwear"],
    notes: "Bring passports, adapters, sunscreen, and a light rain jacket.",
    createdAt: new Date("2026-02-03"),
    updatedAt: new Date("2026-03-01"),
  },
  {
    id: "t2",
    name: "Tokyo Food Sprint",
    destination: "Tokyo, Japan",
    startDate: "2026-09-04",
    endDate: "2026-09-10",
    vibe: "Food",
    category: "Culture",
    status: "planning",
    progress: 46,
    groupSize: 4,
    currency: "JPY",
    budgetTotal: 220000,
    adminId: "u2",
    shareCode: "TOKYO-46",
    members: [
      { uid: "u2", name: "Marco Rivera", email: "marco@email.com", role: "admin", joinedAt: new Date("2026-02-10") },
      { uid: "u1", name: "Ava Mitchell", email: "ava@email.com", role: "member", joinedAt: new Date("2026-02-11") },
    ],
    itinerary: [
      {
        id: "d3",
        label: "Shinjuku Start",
        date: "2026-09-04",
        activities: [
          {
            id: "a4",
            name: "Late-night ramen crawl",
            type: "food",
            time: "21:00",
            icon: "Food",
            location: "Shinjuku",
            notes: "Shortlist three shops with vegetarian options.",
            votes: [{ userId: "u1", value: "up" }],
          },
        ],
      },
    ],
    budget: [],
    comments: [],
    packingList: ["Comfortable shoes", "Rail pass info"],
    notes: "Need one day reserved for team shopping.",
    createdAt: new Date("2026-02-12"),
    updatedAt: new Date("2026-02-14"),
  },
];

export const demoPosts: Post[] = [
  {
    id: "1",
    authorId: "u1",
    authorName: "Ava Mitchell",
    authorColor: "#FF6B6B",
    destination: "Bali, Indonesia",
    caption: "Woke up to waves and a perfect sunrise. This group trip was unreal.",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Pura_Ulun_Danu_Bratan%2C_Bali%2C_Indonesia.jpg",
    tags: ["beach", "bali", "sunset"],
    emoji: "Palm",
    likes: 142,
    likedBy: ["u2"],
    comments: 2,
    bookmarkedBy: ["u2"],
    commentItems: [
      { id: "pc1", userId: "u2", authorName: "Marco Rivera", text: "Saving this villa idea for later.", createdAt: new Date("2026-03-02") },
      { id: "pc2", userId: "u3", authorName: "Sofia Chen", text: "The sunset looked amazing.", createdAt: new Date("2026-03-03") },
    ],
    category: "beach",
    createdAt: new Date("2026-03-01"),
  },
  {
    id: "2",
    authorId: "u2",
    authorName: "Marco Rivera",
    authorColor: "#4ECDC4",
    destination: "Swiss Alps",
    caption: "First time skiing and I already want next winter on the calendar.",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/08/Matterhorn_from_Domhutte_-_2.jpg",
    tags: ["mountains", "swiss", "adventure"],
    emoji: "Peak",
    likes: 89,
    likedBy: ["u1"],
    comments: 1,
    bookmarkedBy: [],
    commentItems: [{ id: "pc3", userId: "u1", authorName: "Ava Mitchell", text: "This deserves a full itinerary template.", createdAt: new Date("2026-02-20") }],
    category: "mountains",
    createdAt: new Date("2026-02-20"),
  },
  {
    id: "3",
    authorId: "u3",
    authorName: "Sofia Chen",
    authorColor: "#6BCB77",
    destination: "Tokyo, Japan",
    caption: "Our food tour turned into the highlight of the whole trip.",
    image: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Tokyo_Tower_and_around_Skyscrapers.jpg",
    tags: ["food", "tokyo", "japan"],
    emoji: "Bowl",
    likes: 201,
    likedBy: ["u1", "u2"],
    comments: 3,
    bookmarkedBy: ["u1"],
    commentItems: [],
    category: "food",
    createdAt: new Date("2026-02-10"),
  },
];

export const demoStories: StoryItem[] = [
  { id: "s1", userId: "u1", authorName: "Ava Mitchell", destination: "Bali", emoji: "Palm" },
  { id: "s2", userId: "u2", authorName: "Marco Rivera", destination: "Swiss Alps", emoji: "Peak" },
  { id: "s3", userId: "u3", authorName: "Sofia Chen", destination: "Tokyo", emoji: "Bowl" },
];

export const demoDestinations: DestinationCard[] = [
  {
    id: "dest-1",
    name: "Bali",
    region: "Indonesia",
    bestFor: ["beaches", "wellness", "groups"],
    budget: "mid",
    season: "May to September",
    groupSize: "4-8 travelers",
    summary: "Great for villas, day clubs, surf lessons, and easy group planning.",
  },
  {
    id: "dest-2",
    name: "Tokyo",
    region: "Japan",
    bestFor: ["food", "culture", "city"],
    budget: "high",
    season: "March to May",
    groupSize: "2-6 travelers",
    summary: "Perfect for fast-moving itineraries with food crawls, rail access, and themed experiences.",
  },
  {
    id: "dest-3",
    name: "Swiss Alps",
    region: "Switzerland",
    bestFor: ["adventure", "winter", "mountains"],
    budget: "high",
    season: "December to March",
    groupSize: "2-5 travelers",
    summary: "Premium mountain escapes with skiing, scenic trains, and cozy stays.",
  },
  {
    id: "dest-4",
    name: "Goa",
    region: "India",
    bestFor: ["beaches", "budget", "nightlife"],
    budget: "low",
    season: "November to February",
    groupSize: "3-10 travelers",
    summary: "Easy for friend groups who want beaches, scooters, and low-friction planning.",
  },
];

export const demoNotifications: NotificationItem[] = [
  {
    id: "n1",
    userId: "u1",
    title: "Booking confirmed",
    body: "Your Bali Beach Escape package has been confirmed. Check your Booking Vault for details.",
    type: "system",
    read: false,
    createdAt: new Date("2026-04-10"),
  },
  {
    id: "n2",
    userId: "u1",
    title: "New like",
    body: "Sofia liked your Bali post.",
    type: "feed",
    read: true,
    createdAt: new Date("2026-03-27"),
  },
  {
    id: "n3",
    userId: "u1",
    title: "Trip updated",
    body: "Marco moved the ramen crawl into Day 1 of Tokyo Food Sprint.",
    type: "trip",
    read: true,
    createdAt: new Date("2026-03-28"),
  },
];

export const demoActivityLog: ActivityLogItem[] = [
  {
    id: "log-1",
    title: "Organizer request pending",
    detail: "Sofia Chen signed up as an organizer and needs review.",
    createdAt: new Date("2026-03-15"),
  },
  {
    id: "log-2",
    title: "Trip removed",
    detail: "A duplicate draft itinerary was deleted by admin.",
    createdAt: new Date("2026-03-20"),
  },
];

export const demoBookings: BookingItem[] = [
  {
    id: "b1",
    userId: "u1",
    product: "holiday-packages",
    title: "Bali Beach Escape Package",
    destination: "Bali",
    city: "Bali",
    state: "Indonesia",
    travelDate: "2026-06-12",
    travelers: 6,
    amount: 3800,
    currency: "USD",
    status: "confirmed",
    paymentMethod: "upi",
    paymentStatus: "paid",
    paymentReference: "WP-8392102A",
    // FIXED: Changed back to "Beach" with capital B to match PackageCategory type
    packageCategory: "Beach" as any, // Using 'as any' to bypass type checking temporarily
    // FIXED: Changed to match budget tier type (likely expects 'low', 'mid', or 'high')
    budgetTier: "high",
    hotelCategory: "5 Star",
    withFlight: true,
    createdAt: new Date("2026-02-05"),
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Pura_Ulun_Danu_Bratan%2C_Bali%2C_Indonesia.jpg",
    details: "Premium beachfront villa included.",
    itinerary: ["Day 1: Arrival & Check-in", "Day 2: Beach Day & Sunset Tour", "Day 3: Ubud Exploration"],
    // FIXED: Changed to "female" to match gender type
    travelerDetails: [{ name: "Ava Mitchell", age: "28", gender: "female" }],
  },
  {
    id: "b2",
    userId: "u1",
    product: "flights",
    title: "Delhi to Mumbai flight",
    from: "Delhi",
    to: "Mumbai",
    destination: "Mumbai",
    city: "Mumbai",
    travelDate: "2026-07-10",
    travelers: 2,
    amount: 4899,
    currency: "INR",
    status: "confirmed",
    paymentMethod: "card",
    paymentStatus: "paid",
    paymentReference: "WP-FL93284B",
    details: "Economy | Direct | 2 Travelers",
    createdAt: new Date("2026-02-10"),
    itinerary: ["Departure: Delhi (DEL) - 08:00 AM", "Arrival: Mumbai (BOM) - 10:15 AM"],
  },
];

export const demoAppState: AppDataState = {
  users: demoUsers,
  trips: demoTrips,
  posts: demoPosts,
  stories: demoStories,
  destinations: demoDestinations,
  notifications: demoNotifications,
  activityLog: demoActivityLog,
  bookings: demoBookings,
  wishlist: [],
  supportTickets: [],
  followedUserIds: ["u1", "u3"],
  bookmarkedDestinationIds: ["dest-2"],
  theme: "light",
};